export const PROFESSIONS = [
  "Accountant",
  "Android Developer",
  "Architect",
  "Backend Developer",
  "Barber / Hair Stylist",
  "Blockchain Developer",
  "Brand Strategist",
  "Calligrapher",
  "Career Coach",
  "Caricature Artist",
  "Chef / Personal Cook",
  "Childcare Provider",
  "Cleaning Professional",
  "Community Manager",
  "Content Writer",
  "Copywriter",
  "Cybersecurity Specialist",
  "Data Analyst",
  "Data Scientist",
  "DevOps Engineer",
  "Digital Marketer",
  "Dog Trainer",
  "Dog Walker",
  "Drone Operator",
  "E-commerce Specialist",
  "Event Manager",
  "Event Photographer",
  "Fashion Designer",
  "Financial Advisor",
  "Fitness Trainer",
  "Florist",
  "Frontend Developer",
  "Full-Stack Developer",
  "Game Developer",
  "Ghostwriter",
  "Graphic Designer",
  "Home Tutor",
  "House Painter",
  "Illustrator",
  "Interior Designer",
  "Interpreter / Translator",
  "iOS Developer",
  "Jewellery Designer",
  "Journalist",
  "Landscape Gardener",
  "Legal Consultant",
  "Life Coach",
  "Machine Learning Engineer",
  "Makeup Artist",
  "Massage Therapist",
  "Motion Designer",
  "Music Teacher",
  "Musician",
  "NFT Artist",
  "Nutritionist",
  "Painter (Fine Art)",
  "Pamphlet Distributor",
  "Personal Trainer",
  "Pet Sitter",
  "Photographer",
  "Podcast Editor",
  "Product Manager",
  "Project Manager",
  "Proofreader",
  "QA Engineer",
  "Real Estate Agent",
  "Research Assistant",
  "SEO Specialist",
  "Smart Contract Developer",
  "Social Media Manager",
  "Solana Developer",
  "Stand-up Comedian",
  "Stylist / Fashion Consultant",
  "Tax Consultant",
  "Technical Writer",
  "Transcriptionist",
  "Travel Planner",
  "Tutor",
  "UI/UX Designer",
  "Video Editor",
  "Videographer",
  "Virtual Assistant",
  "Voice Actor",
  "Web3 Developer",
  "Wedding Planner",
  "Yoga Instructor",
  "Other",
];

export const COUNTRIES = [
  "Argentina",
  "Australia",
  "Austria",
  "Bangladesh",
  "Belgium",
  "Brazil",
  "Canada",
  "Chile",
  "China",
  "Colombia",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Ethiopia",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Hong Kong",
  "Hungary",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Japan",
  "Kenya",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Singapore",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Thailand",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Vietnam",
];
