[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow = "4routMSHngGLj5DbzUozx3Q9f86a5E46SsTDtj7S3Vca"

[provider]
cluster = "devnet"
wallet = '~\.config\solana\id.json'

[scripts]
test = "cargo test"

[hooks]
